### ISSUE TITLE
Fails to create correct datasource for gdbs 

### ISSUE THREAD

**Issue by pheidelb** [WhereGroup/mapqonverter#21]
When adding a GDB, it can happen, that the converter create a path like "[|layername=u|layername=i ...] -> a layername- variable for any letter of the path.

**Comment by xdata-cloud** [comment]
The same problem as pheidelb described.

**Comment by pheidelb** [comment]
Problem should be fixed in the current master. The path creation for features from Gdbs was wrong in FeatureLayerClass.
