### ISSUE TITLE
comtypes failing when running script from toolbox in arcgis

### ISSUE THREAD

**Issue by epochgeo1** [WhereGroup/mapqonverter#27]
I am trying to convert .mxd files into .qgs/.qgz files with the mapqonverter toolbox I loaded into my arc project. The issue seems to be the comtypes. Are there known issues with 1.1.7? Should I change the script to 1.1.8? Is there a more detailed installation guide? Thanks for building this btw!

**Comment by pheidelb** [comment]
Hi,

normally 1.1.7 worked well. Some Questions to circle the problem: 

What Version of Arcmap do you use?

What is the exact error message?

Do you have multiple Python installations - and the comtypes are installed for the right one? 

Greetings!

**Comment by pheidelb** [comment]
Question will be closed, because of Inactivity
