### ISSUE TITLE
Wenn Texte im ArcGIS-Layout doppelt vorkommen, werden sie im QGIS-Layout an eine gemeinsame Stelle positioniert

### ISSUE THREAD

**Issue by Meibes** [WhereGroup/mapqonverter#8]
Wenn z.B. der Text "Datum:" im Layout in ArcGIS mehr als einmal vorhanden, aber an unterschiedlichen Stellen ist, wird zwar für jeden Text ein eigenes Objekt in QGIS angelegt, aber alle Texte sind an exakt der gleichen Stelle bzw überlagern sich

**Comment by pheidelb** [comment]
Der Bug kann auch reproduziert werden und wird demnächst behoben.
